services:
    nginx_php_build:
        container_name: nginx_php_build
        build:
            context: ./
            dockerfile: docker/nginx_php/Dockerfile
        image: nginx-php
        command: echo "Image built successfully"

    nginx_php:
        container_name: nginx_php
        ports:
            - "8080:80"
        build:
            context: .
            dockerfile: docker/nginx_php/dev/Dockerfile-xdebug
        volumes:
            - .:/var/www/html
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:80/healthcheck" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 1s
        restart: on-failure
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            KERNEL_CLASS: App\Kernel
        depends_on:
            - composer_install
            - nginx_php_build

    composer_install:
        container_name: composer_install
        build:
            context: ./
            dockerfile: docker/composer/Dockerfile
        volumes:
            - .:/var/www/html
        command: "install"
