services:

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        restart: on-failure
        depends_on:
            - php
    php:
        container_name: php
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:80/healthcheck" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 1s
        depends_on:
            - composer_install

    composer_install:
        container_name: composer_install
        working_dir: "/var/www/html"
        image: "composer/composer:2.8.9"
        volumes:
            - .:/var/www/html
        command: "install"
